---
all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_password: password
    ansible_port: 2222
    ansible_become: yes
    default_groups:
      - admins
    users:
      - name: "global_admin"
        state: "present"
        groups: ["admins"]
        shell: "/bin/bash"
        password: "{{ vault_global_admin_password }}"
      - name: "global_admin2"
        state: "present"
        groups: ["admins"]
        shell: "/bin/bash"
        password: "{{ vault_global_admin_password }}"
  children:
    dev_servers:
      vars:
        default_groups:
          - admins
          - developers
        users:
          - name: "dev1"
            state: "present"
            groups: ["developers"]
            shell: "/bin/bash"
            password: "{{ vault_dev1_password }}"
            ssh_key_url: "https://github.com/shmakus.keys"
            expiry_date: "2026-06-01"
          - name: "global_admin"
            state: "present"
            groups: ["admins"]
            password: "{{ vault_global_admin_password }}"
          - name: "dev2"
            state: "present"
            groups: ["developers"]
            shell: "/bin/bash"
            ssh_key_url: "https://github.com/shmakus.keys"
            expiry_date: "2026-06-01"
          - name: "dev3"
            state: "present"
            groups: ["developers"]
            shell: "/bin/bash"
            expiry_date: "2025-06-11"
          - name: "global_admin2"
            state: "present"
            groups: ["admins"]
            shell: "/bin/bash"
            password: "{{ vault_global_admin_password }}"
            ssh_key_url: "https://github.com/shmakus.keys"
            expiry_date: "2023-06-01"

      hosts:
        dev_host1:
          ansible_host: localhost
          vars:
            users:
              - name: "local_user"
                state: "present"
                groups: ["developers"]
                shell: "/bin/bash"
                password: "{{ vault_local_user_password }}"
              - name: "dev1"
                state: "present"
                groups: ["developers"]
                shell: "/sbin/nologin"
                ssh_key_url: "https://github.com/shmakus.keys"
                password_lock: no
                password: "{{ vault_dev1_password }}"
                expiry_date: "2026-06-01"
              - name: "global_admin2"
                state: "absent"
                groups: ["admins"]
                shell: "/bin/bash"
                password: "{{ vault_global_admin_password }}"
                ssh_key_url: "https://github.com/shmakus.keys"
                expiry_date: "2026-06-11"